### PR TITLE
Add getConfiguration method in GuzzleExtension

### PR DESCRIPTION
**Pull request by gregurco**
- [x] Bug fix
- [ ] New feature
- [ ] BC breaks
- [ ] Deprecations
- [x] Tests pass

Fixed tickets: [#113]
License: MIT

### CODE REVIEW

**Comment by florianpreusner** [comment]
What is the purpose for this "feature"? Can you describe a little bit why this is helpful in the description of this PR? Thanks in advance!

**Comment by gregurco** [comment]
@florianpreusner so, I market that PR as "Bug fix". First of all it fixes bug from #113. The "feature" is that symfony gives possibility to dump default configuration of bundle from console. You can read more about this feature there: http://symfony.com/doc/current/bundles/configuration.html#dump-the-configuration
There is written that getConfiguration should be implemented, but it isn't:
```
 If you have something different, your Extension class must override the Extension::getConfiguration() method and return an instance of your Configuration.
```

**Comment by florianpreusner** [comment]
Thanks for clarification and your time!

**Comment by florianpreusner** [comment]
Released in v6.1.0 (https://github.com/8p/GuzzleBundle/releases/tag/v6.1.0)

**Pull request merged**
