### PR TITLE
Add tests and improve coverage

### PR DESCRIPTION
**Pull request by gregurco**
Coverage increased from 58.96% to 77.92%

- [ ] Bug fix
- [ ] New feature
- [ ] BC breaks
- [ ] Deprecations
- [x] Tests pass

Fixed tickets: [comma-separated list of tickets fixed by the PR, if any]
License: MIT

### CODE REVIEW

**Comment by florianpreusner** [comment]
@gregurco Thanks a lot for adding more tests. Before I can merge the changes, can you rebase against master, please? Currently your branch is out of date.

Thanks in advance!

**Comment by gregurco** [comment]
@florianpreusner thanks you for fast feedback. Now my branch is up to date and build succeeded.

**Comment by florianpreusner** [comment]
Thanks a lot!

**Comment by florianpreusner** [comment]
Released in v6.1.0 (https://github.com/8p/GuzzleBundle/releases/tag/v6.1.0)

**Pull request merged**
