### PR TITLE
if you cannot log use DevNull Logger

### PR DESCRIPTION
**Pull request by surikman**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | #36 
| License       | MIT
| Doc PR        |

### CODE REVIEW

**Comment by florianpreusner** [comment]
Thanks for the idea and your contribution!
Why not setting parameter "guzzle_bundle.logger.class" directly in project to override the logger class? I think this would also solve the problem. But I still like the idea of providing a "Null" logger.

**Comment by surikman** [comment]
Because, configuration of bundle has "logging" option, bud this option is not used. 
I posted issue https://github.com/8p/GuzzleBundle/issues/36 some time ago, but i can use this in another project. and then, I must create Null logger again... 
Why is there "logging" option ? :)

**Comment by florianpreusner** [comment]
Yes, makes no sense to have a config option that is not used. Let me check that tonight. I have to think about a solution how to handle this. Maybe logger can be deactivated in general by this config.

**Comment by florianpreusner** [comment]
I've tested to set the logger class to another one by using parameters.yml. It works like a charm.
So I don't understand why it is not working for you 😕 

- I like the idea of providing a DevNullLogger. The class needs three more functions: clear(), hasMessages(), getMessages(). Unfortunately Logger.php is not using a custom interface. Maybe this can be refactored to make sure that Logger provides all used functions.
README.md should be updated so users know how to change that (using a custom Logger).
- The logging option should be removed in Configuration.php cause it is not used, as you mentioned.
- Switch statement should not be necessary anymore.

Tell me what you think and if you can change that. I can also do that.

**Comment by surikman** [comment]
As I mentioned in #36 (nick surikman-git was mine)  - set another logger class by using parameters.yml 

> guzzle_bundle.logger.class: Tsm\ServerBundle\Service\DevNullGuzzleLogger

This works fine, but it is not user friendly... 
I think, that logging option is very useful and I refactored Logger, and use LoggerInterface.

**Comment by florianpreusner** [comment]
I agree, it is not very user friendly. 
So, I think it's good to go. Thanks for the changes and your opinion!

**Comment by florianpreusner** [comment]
I will create a new version tonight. I want to cleanup some smaller things first.

**Comment by florianpreusner** [comment]
created v4.6.0: https://github.com/8p/GuzzleBundle/releases/tag/v4.6.0

**Pull request merged**
