### PR TITLE
Improve web profiler toolbar v2 integration

### PR DESCRIPTION
**Pull request by Soullivaneuh**
* The SVG icon is now correctly aligned
* No green color anymore when calls are made to be compliant with native Symfony's collectors
* Improved errored red status integration
* The old toolbar integration is kept thanks to the profiler_markup_version variable

Before:

image

After:

image

image

image

- [x] Enhancement
- [x] Tests pass

License: MIT

References:

* http://symfony.com/blog/new-in-symfony-2-8-redesigned-web-debug-toolbar
* https://github.com/symfony/symfony/blob/2.8/UPGRADE-2.8.md#webprofiler

### CODE REVIEW

**Comment by florianpreusner** [comment]
Nice! Can you rebase your branch? Because of the latest changes there is a small conflict.
Afterwards I will merge and release.
Thanks 👍

**Comment by Soullivaneuh** [comment]
@florianpreusner I did a rebase but let me do some check before merging.

**Comment by Soullivaneuh** [comment]
Ok it works great! Ready to merge for my case @florianpreusner.

**Comment by florianpreusner** [comment]
Going to release a new version soon. I will also do some minor improvements.
Thanks for your contribution!

**Pull request merged**
