### PR TITLE
Fixing preTransaction event replace request object.

### PR DESCRIPTION
**Pull request by mtamazlicaru**
- [x] Bug fix
- [ ] New feature
- [ ] BC breaks
- [ ] Deprecations
- [x] Tests pass

Fixed tickets: [comma-separated list of tickets fixed by the PR, if any]
License: MIT

### CODE REVIEW

**Comment by florianpreusner** [comment]
Released in v6.1.0 (https://github.com/8p/GuzzleBundle/releases/tag/v6.1.0)

**Comment by TheLevti** [comment]
@mtamazlicaru Could you take a look at my last comment please?

**Comment by mtamazlicaru** [comment]
Yeah, i think you are right, i was not using the post event, that is why i didn't see it :)

**Comment by florianpreusner** [comment]
Fixed in PR #131. Released v6.1.1.

**Comment by TheLevti** [comment]
@florianpreusner & @mtamazlicaru thank you for this quick response and fix.

**Pull request merged**
