### PR TITLE
Update travis.yml with PHP 7.1

### PR DESCRIPTION
**Pull request by DonCallisto**
As PHP 7.1 is out since December (6 months) I think is useful to test the codebase against it.

- [ ] Bug fix
- [ ] New feature
- [ ] BC breaks
- [ ] Deprecations
- [x] Tests pass

License: MIT

### CODE REVIEW

**Comment by DonCallisto** [comment]
There is an issue related to ubuntu and HHVM

> HHVM is no longer supported on Ubuntu Precise. Please consider using Trusty with `dist: trusty`.

Let me know how should I move on, if you're interested in 7.1

**Comment by DonCallisto** [comment]
I dine't find a way to `allow_failure` for `hhvm` and `symfony-master`. Suggestions are welcome (keeping in mind that `hhvm` support will be dropped in Symfony 4

**Comment by florianpreusner** [comment]
You are absolutely right! Thanks a lot!

**Comment by DonCallisto** [comment]
@florianpreusner let me know if `travis.yml` could be improved somehow, I'm not that expert but I'm willing to improve the configuration.

**Comment by florianpreusner** [comment]
Well, I think I'm going to remove hhvm in the future because of php 7. I don't see any need to still support/test hhvm. But this is a bigger change for some users, that's why it should be part of a new version.

**Pull request merged**
