### PR TITLE
Possibility to overwrite classnames with service container parameters

### PR DESCRIPTION
**Pull request by sebastianblum**
I created the issue #34 (in german) and here is my code proposal.

please give me feedback that I can work on that pull request.
Sebastian

### CODE REVIEW

**Comment by florianpreusner** [comment]
Cool, didn't know that this is possible.
Checking details later and will provide some feedback.

**Comment by florianpreusner** [comment]
Why are you using fake classes instead of mocking?

**Comment by sebastianblum** [comment]
I wrote a lot of tests for debugging and then I left these tests.

I don't want to mock the container and before, I used stdClass while debugging.
With the Fake classes I will show, that I can overwrite the class parameter and I will get an instance of that class.

I don't know a better pattern to test that.

**Comment by sebastianblum** [comment]
the symfony team uses stdClass and at the end a FooClass
https://github.com/symfony/symfony/blob/master/src/Symfony/Component/DependencyInjection/Tests/ContainerBuilderTest.php#L721

**Comment by florianpreusner** [comment]
:+1:  

Thanks for contributing!

**Pull request merged**
