### PR TITLE
Add support for 'auth' option

### PR DESCRIPTION
**Pull request by shadypierre**
Add support for the missing option [auth](http://docs.guzzlephp.org/en/latest/request-options.html#auth) and fix indentation.

See previous PR #17

### CODE REVIEW

**Comment by florianpreusner** [comment]
Thanks for your contribution!

**Comment by JarJak** [comment]
build is failling now

**Comment by shadypierre** [comment]
I don't know why build is passed only for php 5.5 :/ any idea ?

**Comment by florianpreusner** [comment]
It seems to be related to the PHPUnit version. When using PHP 5.6 PHPUnit 5.x is used. I think it is not related to the commit cause there was no change.

**Comment by florianpreusner** [comment]
This seems to be the issue: https://github.com/sebastianbergmann/phpunit/issues/1883

**Pull request merged**
