### PR TITLE
Headers configuration that allow underscores

### PR DESCRIPTION
**Pull request by PWalkow**
- [X] Bug fix
- [ ] New feature
- [ ] BC breaks
- [ ] Deprecations
- [X] Tests pass

Fixed tickets: [#101 - Params in header]
License: MIT

### CODE REVIEW

**Comment by florianpreusner** [comment]
Symfony Doc: http://symfony.com/doc/current/components/config/definition.html#array-node-options

**Comment by florianpreusner** [comment]
Thanks for this improvement and your effort, @PWalkow!

**Comment by PWalkow** [comment]
@florianpreusner Let us know please if this branch will be also released at 5.* tag that is used by stable version in packagist.

**Comment by florianpreusner** [comment]
Yip, will be released this evening. 👍

**Comment by florianpreusner** [comment]
Released https://github.com/8p/GuzzleBundle/releases/tag/v5.4.0

**Comment by PWalkow** [comment]
Thank you @florianpreusner but looks like packagist need an update as well to pick up latest 5.4 version

**Comment by florianpreusner** [comment]
Fixed! Strange that I had to this manually. Thanks for the hint, @PWalkow!
https://packagist.org/packages/eightpoints/guzzle-bundle

**Comment by florianpreusner** [comment]
Because of some issues I removed v5.4 and released a new major version 6.0.
- https://github.com/8p/GuzzleBundle/issues/112
- https://github.com/8p/GuzzleBundle/pull/106#issuecomment-319965075

**Pull request merged**
