### PR TITLE
[RFC] Improvements to better support Symfony Flex

### PR DESCRIPTION
**Pull request by ruudk**
I'm working on a new project that uses Symfony Flex / 4.0 (for testing purposes). I found out that this bundle doesn't really work nicely with it. As Symfony Flex / 4.0 will be [released in november](http://symfony.com/roadmap?version=4.0#checker) I thought it would be good to refactor this bundle a bit to better support it.

This is just a RFC, because I want to know what your vision is for the bundle.

A couple of things I changed:

* Move from PSR-0 to PSR-4
* Rename GuzzleBundle to EightPointsGuzzleBundle to better follow the standard. This is not the official GuzzleBundle and thus should use the namespace prefix. It's also easier for Symfony Flex to automatically install this. Without this change, Symfony Flex tries to install 2 bundles:
```php
    'EightPoints\Bundle\GuzzleBundle\GuzzleBundle' => ['all' => true],
    'EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle' => ['all' => true],
```
* Fix all the template references by from `WebProfilerBundle:Profiler:layout.html.twig` to `@WebProfiler/Profiler/layout.html.twig`

Todo:
- [x] Change all service aliases as well to `eight_points_guzzle`

### CODE REVIEW

**Comment by ruudk** [comment]
@florianpreusner Any ideas how to proceed? I'd like to improve this bundle to better support Symfony Flex

**Comment by florianpreusner** [comment]
Hi @ruudk, first of all: Thanks a lot for your time and effort. Unfortunately there was no time to review this PR the last days. I will try my best to share my opinion asap. My first impression is very good!

**Comment by ruudk** [comment]
@florianpreusner Thanks! Let me know. I will fix the tests once I have a green light :)

**Comment by florianpreusner** [comment]
Hi @ruudk! I checked your changes. I like them a lot! 👍  

It would be awesome if you can change also the service aliases. We should merge the changes to v7. There will be some other changes too, for example: I want to drop PHP 5 support (https://github.com/8p/GuzzleBundle/pull/100).

**Comment by ruudk** [comment]
@florianpreusner haha, I was just visiting this PR to check for progress and there is your reply! Great :D 

Do you mean the prefixed name of the services? 
`guzzle_bundle` > `eight_points_guzzle_bundle`

**Comment by florianpreusner** [comment]
@ruudk Right!

**Comment by ruudk** [comment]
@florianpreusner It's green!

**Comment by florianpreusner** [comment]
Nice! Thanks for your time!
What do you think about integrating your changes into v7? So I would like to change the base branch. Unfortunately, that means that some adjustments have to be done to be compatible with v7 (PHP 7) branch 😕

**Comment by ruudk** [comment]
@florianpreusner Done, rebased on v7.

**Comment by florianpreusner** [comment]
Going to release v7 by the end of this month. Going to replace master by v7 in two weeks.

**Comment by gregurco** [comment]
> Rename GuzzleBundle to EightPointsGuzzleBundle to better follow the standard. This is not the official > GuzzleBundle and thus should use the namespace prefix. It's also easier for Symfony Flex to automatically install this. Without this change, Symfony Flex tries to install 2 bundles:
>     'EightPoints\Bundle\GuzzleBundle\GuzzleBundle' => ['all' => true],
>     'EightPoints\Bundle\GuzzleBundle\EightPointsGuzzleBundle' => ['all' => true],

**Comment by ruudk** [comment]
Great! Already thought it was a bug in flex. Still think this change is good to just better follow other bundles. Especially since this is not an official bundle.

**Comment by florianpreusner** [comment]
Going to rename once we merged new changes into master.

**Pull request merged**
